[package]
name = "ticc_discord_bot_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
poise = "0.6.1"
dotenv = "0.15.0"
redis = "0.27.2"
serde = "1.0.204"
serde_json = "1.0.120"
